In [3]:
import numpy as np
import pandas as pd

In [15]:
s = pd.Series(data=np.linspace(1,10,5),index=list('ABCEF'),name='age')
s

A     1.00
B     3.25
C     5.50
E     7.75
F    10.00
Name: age, dtype: float64

In [16]:
s.A,s[0], bool(s.A==s[0]), s.loc['A'],s.iloc[0]

(1.0, 1.0, True, 1.0, 1.0)

In [18]:
s['B':'E'], s[1:4]

(B    3.25
 C    5.50
 E    7.75
 Name: age, dtype: float64,
 B    3.25
 C    5.50
 E    7.75
 Name: age, dtype: float64)

In [22]:
s.values

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
s.index

Index(['A', 'B', 'C', 'E', 'F'], dtype='object')

In [26]:
s.size

5

In [27]:
s.shape

(5,)

In [28]:
s.name

'age'

In [29]:
s.ndim

1

In [24]:
s.value_counts()

age
1.00     1
3.25     1
5.50     1
7.75     1
10.00    1
Name: count, dtype: int64

In [31]:
d = s.to_frame(name='orange')
d

orange
A    1.00
B    3.25
C    5.50
E    7.75
F   10.00

In [36]:
d.shape, d.ndim, d.values, 

((5, 1),
 2,
 array([[ 1.  ],
        [ 3.25],
        [ 5.5 ],
        [ 7.75],
        [10.  ]]))

In [38]:
d.keys()

Index(['orange'], dtype='object')

In [39]:
df = pd.DataFrame(
    data={
        'name':['a', 'b', 'c', 'd', 'e'],
        'count': [10, 12, 14, 16, 18],
        'plus':['A', 'B', 'C', 'D', 'E']
    }
)
df

name  count plus
0    a     10    A
1    b     12    B
2    c     14    C
3    d     16    D
4    e     18    E

In [44]:
df1 = pd.DataFrame(
    data=np.eye(5,5),
    columns=['a', 'b','c','d', 'e']

)
df1

a    b    c    d    e
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [49]:
df1.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [54]:
df.to_csv('1.csv',index=False, sep=',')

In [53]:
df.to_sql('1')

TypeError: to_sql() missing 1 required positional argument: 'con'

In [4]:
age = [18,19,20]
age_np = np.array(age, dtype=np.float32)
age_np

array([18., 19., 20.], dtype=float32)

In [8]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones(age_np.shape, dtype=np.int_)

array([1, 1, 1])

In [12]:
np.eye(2,3,0)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [9]:
np.full(shape=(2,2),fill_value=5)

array([[5, 5],
       [5, 5]])

In [14]:
np.linspace(start=1,stop=10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(start=1,stop=10,num=10,endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [16]:
np.arange(start=1,stop=10, step=1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 索引