In [7]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [15]:
mat_1 = torch.rand((4,5)).to(device)
mat_2 = torch.rand((5,4)).to(device)
mat_res = mat_1 @ mat_2
mat_res.shape

torch.Size([4, 4])

In [25]:
mat_2 = torch.rand((5,4))
a = mat_2.transpose(1,0)
a

tensor([[0.4681, 0.2252, 0.9084, 0.8149, 0.5012],
        [0.4526, 0.3134, 0.3927, 0.7180, 0.0953],
        [0.6256, 0.0612, 0.9739, 0.1663, 0.9252],
        [0.2053, 0.8767, 0.4849, 0.5040, 0.1924]])

In [31]:
import torch.nn.functional as F

b = F.softmax(a, dim=0)
b

tensor([[0.2548, 0.2058, 0.3012, 0.3161, 0.2545],
        [0.2509, 0.2248, 0.1799, 0.2869, 0.1696],
        [0.2983, 0.1747, 0.3217, 0.1653, 0.3889],
        [0.1959, 0.3948, 0.1972, 0.2317, 0.1869]])

In [34]:
max(b[:,1])

tensor(0.3948)

In [35]:
import torch
import torch.nn as nn
class LanguageModel(nn.Module):
    def __init__(self, vocab_size,  *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.token_embedding = nn.Embedding(vocab_size, vocab_size)
        
    def forward(self, tokens=None):
        logits = self.token_embedding(tokens)

        if tokens is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = tokens.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss
    

    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(index)
            logits = logits[:, -1, :] 
            probs = F.softmax(logits, dim=-1)
            index_next = torch.multinomial(probs, num_samples=1)
            index = torch.cat((index, index_next), num_samples=1)
        return 
    
model = LanguageModel(512).to(device)

        

In [37]:
content = torch.randint(0, 512, (1, 10)).to(device)
content

tensor([[453, 106, 494, 436, 350, 166, 284, 441, 287, 477]], device='cuda:0')